CREATE DATABASE IF NOT EXISTS FUGOWORLD;

CREATE USER IF NOT EXISTS 'fugoworld'@'localhost' IDENTIFIED WITH mysql_native_password BY 'fugoworld';

GRANT ALL PRIVILEGES ON FUGOWORLD.* TO 'fugoworld'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;
